version: "3"

services:
  memes-api:

    env_file:
      - .env

    build:
      context: csharp-src/MemesApi/MemesApi/
      dockerfile: Dockerfile
    
    ports:
      - 9999:9999
    volumes:
      - ${STATIC_FILES_PATH}:/app/static

    restart: always

  bot:
    env_file:
      - .env
    
    build:
      context: python-src/
      dockerfile: Dockerfile

    