apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-volume

spec:
  capacity:
    storage: 5Gi
  
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  local:
    path: /mnt/c/Projects/memosi_generator/static

  
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - example-node