global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    cluster_name: prometheus-monitor

scrape_configs:
- job_name: prometheus
  scrape_interval: 60s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

- job_name: 'cadvisor'
  scrape_interval: 10s
  static_configs:
  - targets: ['cadvisor:8080']

- job_name: 'node-exporter'
  scrape_interval: 10s
  static_configs:
  - targets: ['node-exporter:9100']